baseURL = "https://penninesoaringclub.github.io/newsletter/"
defaultContentLanguage = "en"
languageCode = "en"
publishDir = 'docs'

title = "PSC Newsletters"

theme = ["gokarna", "hugo-shortcode-gallery"]

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
  footer = "Pennine Soaring Club"
  description = "News from the Pennine Soaring Club"
  avatarURL = "/images/psc-logo.png"
  AvatarAltText = "avatar"
  avatarSize = "size-m"
  ShowBackToTopButton = true # true or false for "back to top" button on posts
  customHeadHTML = ""

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "post"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = "<span data-feather='book-open'></span>"

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Newsletters"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "psc"
    name = "PSC Home"
    url = "http://www.penninesoaringclub.org.uk/"
    weight = 2
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='home'></span>"